spring.application.name=demo
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Connect to the PostgreSQL service running on your machine (port 5432)
spring.datasource.url=jdbc:postgresql://localhost:5432/audit_db?
spring.datasource.username=postgres
spring.datasource.password=anashaju

# Automatically create or update tables based on your Java models
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

postgresql://kleckadvice_db_user:loE0YklgROy7hcF4O33pyVvIWMMAi8Ey@dpg-dano2dijnfac7399erjg-a/kleckadvice_db